TARGET := iphone:clang:6.1:6.0

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = Parroting-back

MyApp_FILES = main.m XXAppDelegate.m XXRootViewController.m
MyApp_FRAMEWORKS = UIKit CoreGraphics
MyApp_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/application.mk
