TARGET := iphone:clang:6.1:6.0

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = first-internet

Parroting-back_FILES = main.m FIRootViewController.m
Parroting-back_FRAMEWORKS = UIKit CoreGraphics
Parroting-back_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/application.mk
